// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Suave")>]
[<assembly: AssemblyDescriptionAttribute("Suave — a smooth, open source, F# web server.")>]
[<assembly: AssemblyVersionAttribute("2.6.0")>]
[<assembly: AssemblyFileVersionAttribute("2.6.0")>]
[<assembly: AssemblyMetadataAttribute("Commit","ea5d51")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Suave"
    let [<Literal>] AssemblyDescription = "Suave — a smooth, open source, F# web server."
    let [<Literal>] AssemblyVersion = "2.6.0"
    let [<Literal>] AssemblyFileVersion = "2.6.0"
    let [<Literal>] AssemblyMetadata_Commit = "ea5d51"
